version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ferdinand
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: indexeur
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@esgi.fr
      PGADMIN_DEFAULT_PASSWORD: myadminpassword
    ports:
      - "5050:80"
  hasura:
    container_name: hasura
    image: hasura/graphql-engine
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://ferdinand:mysecretpassword@db:5432/indexeur
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db